title: ReaDDy documentation
email: readdyadmin@lists.fu-berlin.de
description: >
  Documentation of ReaDDy, the particle-based reaction-diffusion simulator
baseurl: ""
#url: "https://readdy.github.io/readdy_documentation/"
github_username:  readdy

# Build settings
markdown: kramdown
theme: minima
