title: ReaDDy documentation
email: readdyadmin@lists.fu-berlin.de
description: >
  Documentation of ReaDDy, the particle-based reaction-diffusion simulator
baseurl: /readdy_documentation
url: https://readdy.github.io
github_username: readdy
sass:
  sass_dir: _sass
include:
  - "_docpages"
  - "_docentries"
kramdown:
  input: GFM
  syntax_highlighter: rouge
collections:
  docpages:
    output: true
    permalink: /:collection/:path/
  docentries:
    output: false # docentries' content is included when building docpage
defaults:
  -
    scope:
      path: ""
      type: "docpages"
    values:
      layout: "docpage"
      title: ""
      entries: []
  -
    scope:
      path: ""
      type: "docentries"
    values:
      title: ""