title: ReaDDy documentation
email: readdyadmin@lists.fu-berlin.de
description: >
  Documentation of ReaDDy, the particle-based reaction-diffusion simulator
baseurl: /readdy_documentation
url: https://readdy.github.io
github_username: readdy
sass:
  sass_dir: _sass
include:
  - "_tutorials"
kramdown:
  input: GFM
  syntax_highlighter: rouge
collections:
  reactions:
    output: false
  potentials_order1:
    output: false
  potentials_order2:
    output: false
  observables:
    output: false
  tutorials:
    output: true
    permalink: /:collection/:path/
defaults:
  -
    scope:
      type: "tutorials"
    values:
      layout: "tutorial"
      title: "defaulttitle"
